"""
VoyageMind Models Package

Exports database and schema models for easy importing.
"""

from app.models.database import (
    User,
    Session,
    Trip,
    Itinerary,
    Flight,
    Hotel,
    Attraction,
    WeatherData,
    AgentLog,
    SessionLocal,
    engine,
    Base,
    get_db,
    create_tables,
    drop_tables,
    reset_database,
)

from app.models.schemas import (
    AccommodationRequest,
    AccommodationResult,
    UserBase,
    UserCreate,
    User as UserSchema,
    TripInput,
    FlightSegment,
    FlightOption,
    HotelOption,
    WeatherForecast,
    Attraction as AttractionSchema,
    DailyItinerary,
    TravelPlan,
    TravelPlanResponse,
    AgentStep,
    StreamingResponse,
    SessionData,
    ErrorResponse,
    ValidationError,
)

__all__ = [
    # Database
    "User",
    "Session",
    "Trip",
    "Itinerary",
    "Flight",
    "Hotel",
    "Attraction",
    "WeatherData",
    "AgentLog",
    "SessionLocal",
    "engine",
    "Base",
    "get_db",
    "create_tables",
    "drop_tables",
    "reset_database",
    # Schemas
    "AccommodationRequest",
    "AccommodationResult",
    "UserBase",
    "UserCreate",
    "UserSchema",
    "TripInput",
    "FlightSegment",
    "FlightOption",
    "HotelOption",
    "WeatherForecast",
    "AttractionSchema",
    "DailyItinerary",
    "TravelPlan",
    "TravelPlanResponse",
    "AgentStep",
    "StreamingResponse",
    "SessionData",
    "ErrorResponse",
    "ValidationError",
]
